services:
  - type: web
    name: bachelo
    runtime: node
    buildCommand: cd Bachelo && npm install && npm run build
    startCommand: cd Bachelo && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: CRON_SECRET
        generateValue: true